Repository visgl/loaders.gl, pull requests merged in 2021-08, with the labels that each got.

#1725 chore(I3S-Debug): memory stats positioning change
  examples/website/i3s/app-debug.js
  examples/website/i3s/app.js
  examples/website/i3s/components/control-panel.js
  examples/website/i3s/components/debug-option-group.js
  examples/website/i3s/components/debug-panel.js
  examples/website/i3s/components/memory-stats.js
  examples/website/i3s/components/semantic-validator.js
  examples/website/i3s/components/toggle-switch.js
Labels: chore

#1730 chore(wkt): improved wkt typings
  modules/wkt/src/lib/encode-wkt.ts
  modules/wkt/test/wkt/encode-wkt.spec.js
Labels: chore

#1737 chore(I3S-Debug): UI changing - Debug Panel
  examples/website/i3s/app-debug.js
  examples/website/i3s/app.js
  examples/website/i3s/components/checkbox.js
  examples/website/i3s/components/control-panel.js
  examples/website/i3s/components/debug-option-group.js
  examples/website/i3s/components/debug-panel.js
  examples/website/i3s/components/map-info.js
  examples/website/i3s/components/memory-stats.js
  examples/website/i3s/components/semantic-validator.js
  examples/website/i3s/components/styles.js
  examples/website/i3s/components/toggle-switch.js
  examples/website/i3s/constants.js
Labels: UI/UX

#1757 chore(I3S): change memory stats styles
  examples/website/i3s/app.js
Labels: UI/UX

#1764 docs(tile-converter): fix dockerhub links
  modules/tile-converter/docs/cli-reference/tile-converter.md
Labels: docs

#1763 chore(I3S-Debug): add tool bar functionality
  examples/website/i3s/app-debug.js
  examples/website/i3s/app.js
  examples/website/i3s/components/attributes-panel.js
  examples/website/i3s/components/control-panel.js
  examples/website/i3s/components/debug-panel.js
  examples/website/i3s/components/map-info.js
  examples/website/i3s/components/semantic-validator.js
  examples/website/i3s/components/styles.js
  examples/website/i3s/components/tool-bar.js
Labels: UI/UX

#1770 chore(I3S-Debug): buttons highlighting
  examples/website/i3s/components/tool-bar.js
Labels: UI/UX

#1771 Fix toggle buttons I3S-Debug-App
  examples/website/i3s/components/debug-panel.js
Labels: UI/UX

#1772 I3s-Debug-App - Fix semantic validator layout
  examples/website/i3s/components/semantic-validator.js
Labels: UI/UX

#1774 I3S-Debug-App - Fix debug panel layout
  examples/website/i3s/components/debug-panel.js
Labels: UI/UX

#1777 I3S-Apps - Fix memory widget layout
  examples/website/i3s/app-debug.js
  examples/website/i3s/app.js
Labels: UI/UX

#1778 I3S-Debug-App - Fix Info panel layout
  examples/website/i3s/components/map-info.js
Labels: UI/UX

#1779 I3S-Debug-App - Disable info picking tooltips for mobile
  examples/website/i3s/app-debug.js
  examples/website/i3s/package.json
Labels: UI/UX

#1775 chore(I3S-Debug): add tooltips
  examples/website/i3s/components/tool-bar.js
Labels: UI/UX

#1780 I3S-App - Commont layout fixes
  examples/website/i3s/app-debug.js
  examples/website/i3s/app.js
  examples/website/i3s/components/attributes-panel.js
  examples/website/i3s/components/semantic-validator.js
Labels: UI/UX

#1768 chore(examples): add inertia flag to deck.gl controller
  examples/website/3d-tiles/app.js
  examples/website/i3s/app-debug.js
  examples/website/i3s/app.js
  examples/website/pointcloud/app.js
Labels: chore

#1781 I3S-Debug-App - Safari layout fixes
  examples/website/i3s/components/debug-panel.js
  examples/website/i3s/components/tile-validator.js
Labels: UI/UX

#1791 chore(examples) improving code after code review
  examples/website/geospatial/.babelrc
  examples/website/geospatial/components/parse-file.js
  examples/website/geospatial/examples.js
  examples/website/geospatial/webpack.config.js
Labels: chore

#1790 I3S-Debug-App - Fix toolbar layout
  examples/website/i3s/app-debug.js
  examples/website/i3s/components/map-info.js
  examples/website/i3s/components/tool-bar.js
  examples/website/i3s/index.html
  examples/website/i3s/package.json
Labels: UI/UX

#1787 chore(textures): remove unnecessary dependencies
  modules/geotiff/package.json
  modules/textures/package.json
  modules/zarr/package.json
Labels: dependencies
